# dotenvでやったので必要ないかも。。。
default_twitter: &default_twitter
#  twitter_api_key:
#  twitter_api_secret:

development:
  secret_key_base: fc039e72cd3f20b79b1eb6ccb54dc20e9d10ff2c34b5c3a6bc9fca43fa3982970bdfccd499a9932c943b81018f57256bbc13a773b5e4ebc86d799b6ec6659c4d
  <<: *default_twitter

test:
  secret_key_base: 7570aa9137f2ff8b6c97552021d6488e2ed96dbfd072629b10a6c1c9ead06176ce7e61172cd6515c9bbc4222cca90db68d7bbe3b6847f96827420507b09f909c
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>